String sqlCreateTable = """
  CREATE TABLE USUARIO( 
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL DEFAULT '',
    SALT TEXT NOT NULL DEFAULT '',
    PASSWORD TEXT NOT NULL DEFAULT '',
    LOGIN TEXT NOT NULL DEFAULT '',
    EMAIL TEXT NOT NULL DEFAULT '',
    DATETIME DATA NOT NULL DEFAULT CURRENT_DATE,
    STATUS TEXT NOT NULL DEFAULT '',
    TELEFONE TEXT NOT NULL DEFAULT ''  
  );
""";